## Numpy

1. Создайте вектор состоящий из чисел от 0 до 11 включительно. 

In [3]:
import numpy as np
exampleVector = np.arange(0, 12)
exampleVector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

2. Измените размерность вектора и превратите его в матрицу 3 х 4

In [15]:
exampleVector = exampleVector.reshape((3, 4))
exampleVector

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

3. Найдите произведение полученной матрицы и вектора [2, 3, 5, 6]

In [17]:
exampleVector * np.array([2, 3, 5, 6]) #поэлементное (точнее даже построчное)
exampleVector.dot(np.array([2, 3, 5, 6])) #через скалярное произведение

array([ 31,  95, 159])

4. Из матрицы из пункта 2 сделайте квадратную матрицу состоящую из строк с индексами 0, 1, 3 
<br><br><b>(имелось в виду столбцов?)<b>
  

In [28]:
newVector = exampleVector[0:3, [0, 1, 3]]
newVector

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

5. Найдите обратную матрицу к полученной в пункте 4.
<br><br><b>Не можем найти обратную матрицу, т.к. детерминат равен 0<b>
    <br><b>Изменим матрицу<b>

In [36]:
newVector = exampleVector[1:3, [1, 2]]
invVector = np.linalg.inv(newVector)
print(newVector)
print(invVector)

[[ 5  6]
 [ 9 10]]
[[-2.5   1.5 ]
 [ 2.25 -1.25]]


6. Проверьте является ли она обратной?

In [38]:
newVector.dot(invVector)

array([[ 1.00000000e+00,  8.88178420e-16],
       [-1.77635684e-15,  1.00000000e+00]])

## Pandas

1. Загрузите данные из https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv в DataFrame. Воспользуйтесь одним из способов предложенных на занятии.

In [41]:
pip install wget

  Created wheel for wget: filename=wget-3.2-cp37-none-any.whl size=9687 sha256=ec4d3332b2423de30f3f26b37e69cb442ac9151d55e803518c11a5901d685df9
  Stored in directory: C:\Users\likei\AppData\Local\pip\Cache\wheels\40\15\30\7d8f7cea2902b4db79e3fea550d7d7b85ecb27ef992b618f3f
Successfully built wget
Note: you may need to restart the kernel to use updated packages.


In [42]:
import wget
wget.download('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv', 'data.csv')

'data.csv'

2. Выведите несколько первых строк таблицы. 

In [60]:
import pandas as pd
df = pd.read_csv('data.csv')
df.head(3)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350

3. Отфильруйте машины по марке и оставьте только строки с автомобилями BMW. 

In [53]:
df = df[df['Make']=='BMW']

4. Найдите среднюю стоимость автомобиля BMW и выведите данное значение с точность до двух знаком после запятой.

In [57]:
round(df['MSRP'].mean(), 2)

61546.76

5. Определите каких автомобилей больше с ручной коробокой передач или автоматической?

In [61]:
'MANUAL' if (df['Transmission Type'] == 'MANUAL').sum() > (df['Transmission Type'] == 'AUTOMATIC').sum() else 'AUTOMATIC'

'AUTOMATIC'